-- SQL Query to Extract Inventory Organization name table in oracle Fusion

SELECT to_char(HOU.ORGANIZATION_ID) ORGANIZATION_ID,
HOU.NAME ORGANIZATION_NAME,
MP.ORGANIZATION_CODE ORGANIZATION_CODE,
to_char(LGR.LEDGER_ID) SET_OF_BOOKS_ID,
to_char(LGR.CHART_OF_ACCOUNTS_ID) CHART_OF_ACCOUNTS_ID,
LGR.CURRENCY_CODE,
LGR.PERIOD_SET_NAME,
DECODE(HOI1.STATUS, 'A', 'Y', 'N') INVENTORY_ENABLED_FLAG,
BU.BU_NAME BUSINESS_UNIT_NAME,
to_char(MP.BUSINESS_UNIT_ID) BUSINESS_UNIT_ID,
to_char(MP.LEGAL_ENTITY_ID) LEGAL_ENTITY_ID,
HOI1.CLASSIFICATION_CODE
FROM HR_ALL_ORGANIZATION_UNITS_X HOU,
HR_ORG_UNIT_CLASSIFICATIONS_X HOI1,
INV_ORG_PARAMETERS MP,
GL_LEDGERS LGR,
FUN_ALL_BUSINESS_UNITS_V BU
WHERE HOU.ORGANIZATION_ID = HOI1.ORGANIZATION_ID(+)
AND HOU.ORGANIZATION_ID = MP.ORGANIZATION_ID(+)
AND MP.BUSINESS_UNIT_ID = BU.BU_ID(+)
AND BU.PRIMARY_LEDGER_ID = LGR.LEDGER_ID(+)



-- Business Organization name table in oracle Fusion
1. HR_ALL_ORGANIZATION_UNITS_F
2.HR_ORGANIZATION_UNITS_F_TL
3.HR_ORGANIZATION_INFORMATION_F
4.HR_ORG_UNIT_CLASSIFICATIONS_F

--SQL query to extract Organization name table in oracle Fusion
select to_char(hao.organization_id) as bu_id,haot.name,to_char(hao.business_group_id) business_group_id
FROM
HR_ALL_ORGANIZATION_UNITS_F hao,
HR_ORGANIZATION_UNITS_F_TL haot
WHERE
hao.ORGANIZATION_ID = haot.ORGANIZATION_ID
AND hao.EFFECTIVE_START_DATE = haot.EFFECTIVE_START_DATE
AND hao.EFFECTIVE_END_DATE = haot.EFFECTIVE_END_DATE
AND TRUNC(SYSDATE) BETWEEN hao.EFFECTIVE_START_DATE AND hao.EFFECTIVE_END_DATE
AND haot.LANGUAGE='US'
AND haot.name = :P_BU_NAME


-- Value Sets Query
SELECT vs.value_set_code,
vb.value,
vt.description
FROM FND_VS_VALUE_SETS vs,
FND_VS_VALUES_B vb,
FND_VS_VALUES_TL vt
WHERE 1=1
AND vs.value_set_code = :VALUE_SET_CODE
AND vs.value_set_id = vb.value_set_id
AND vt.value_id = vb.value_id
AND vt.language = USERENV(‘LANG’)
order by vb.value







VALIDATION_TYPE

DEP - 5
INDEP - 146
FORMAT - 380
TABLE - 1475

6th floor - 70 red, 28 blue (98)
5th floor - 96+32 red, 25 blue (153)
Total - 251