-- View
select * from INV_ORG_PARAMETERS_V;


-- Detailed Query
SELECT to_char(HOU.ORGANIZATION_ID) ORGANIZATION_ID,
HOU.NAME ORGANIZATION_NAME,
MP.ORGANIZATION_CODE ORGANIZATION_CODE,
to_char(LGR.LEDGER_ID) SET_OF_BOOKS_ID,
to_char(LGR.CHART_OF_ACCOUNTS_ID) CHART_OF_ACCOUNTS_ID,
LGR.CURRENCY_CODE,
LGR.PERIOD_SET_NAME,
DECODE(HOI1.STATUS, 'A', 'Y', 'N') INVENTORY_ENABLED_FLAG,
BU.BU_NAME BUSINESS_UNIT_NAME,
to_char(MP.BUSINESS_UNIT_ID) BUSINESS_UNIT_ID,
to_char(MP.LEGAL_ENTITY_ID) LEGAL_ENTITY_ID,
HOI1.CLASSIFICATION_CODE
FROM HR_ALL_ORGANIZATION_UNITS_X HOU,
HR_ORG_UNIT_CLASSIFICATIONS_X HOI1,
INV_ORG_PARAMETERS MP,
GL_LEDGERS LGR,
FUN_ALL_BUSINESS_UNITS_V BU
WHERE 1=1
AND MP.organization_code = 'AVP1'
AND HOU.ORGANIZATION_ID = HOI1.ORGANIZATION_ID(+)
AND HOU.ORGANIZATION_ID = MP.ORGANIZATION_ID(+)
AND MP.BUSINESS_UNIT_ID = BU.BU_ID(+)
AND BU.PRIMARY_LEDGER_ID = LGR.LEDGER_ID(+)