/****************************************
-- Supplier Tax Id's
****************************************/
select psv.VENDOR_NAME, psv.SEGMENT1 SUPPLIER_NUMBER,psp.INCOME_TAX_ID, psv.type_1099
 from  POZ_SUPPLIERS_PII psp,POZ_SUPPLIERS_V psv
 WHERE 1=1
 and psp.VENDOR_ID=psv.vendor_id
and psv.type_1099 is not null;



/****************************************
-- Supplier Extract for PPA Audit report
****************************************/
SELECT  1 + FLOOR( (ROW_NUMBER() OVER (ORDER BY ( SELECT 0 FROM DUAL) ) / :P_KEY_ROWS) ) KEY
	  ,POS.VENDOR_ID
	  ,PSA.CREATED_BY
      ,POS.VENDOR_NAME
	  ,POS.SEGMENT1 VENDOR_NUMBER
	  ,TO_CHAR(POS.CREATION_DATE, 'MM/DD/YYYY') VENDOR_CREATION_DATE
	  ,PSA.ADDRESS1
	  ,PSA.ADDRESS2
	  ,PSA.ADDRESS3
	  ,PSA.COUNTRY
	  ,PSA.FAX_COUNTRY_CODE||PSA.FAX_PHONE_AREA_CODE||PSA.FAX_PHONE_NUMBER FAX_NUMBER
	  ,PSA.PHONE_COUNTRY_CODE||PSA.PHONE_AREA_CODE||PSA.PHONE_NUMBER||PSA.PHONE_EXTENSION PHONE_NUMBER
	  ,PSA.EMAIL_ADDRESS
	  ,CASE WHEN POS.ENABLED_FLAG = 'Y' 
			THEN 'ACTIVE' 
			ELSE 'INACTIVE'
	   END STATUS 
	  ,PSA.POSTAL_CODE
	  ,PSA.CITY
	  ,NVL(POZS.INVOICE_CURRENCY_CODE, POZS.PAYMENT_CURRENCY_CODE) CURRENCY_CODE
	  ,IPMT.PAYMENT_METHOD_CODE
	  --,AT.NAME
	  --,AT.DESCRIPTION
	  ,ZXR.REGISTRATION_NUMBER	  
FROM  POZ_SUPPLIERS_V POS
     ,POZ_SUPPLIER_ADDRESS_V PSA 
	 ,POZ_SUPPLIER_SITES_ALL_M POZS
	 ,IBY_EXTERNAL_PAYEES_ALL IBY
	 ,IBY_EXT_PARTY_PMT_MTHDS IPMT
	 ,ZX_PARTY_TAX_PROFILE TAX
	 ,ZX_REGISTRATIONS ZXR
	-- ,AP_TERMS AT
WHERE 1 = 1
  AND POS.VENDOR_ID       = PSA.VENDOR_ID
  AND POS.PARTY_ID = PSA.PARTY_ID(+)
  AND PSA.VENDOR_ID 	  = POZS.VENDOR_ID(+)
  AND PSA.PARTY_SITE_ID = POZS.PARTY_SITE_ID(+)
  AND POZS.VENDOR_SITE_ID = IBY.SUPPLIER_SITE_ID(+)
  AND IBY.EXT_PAYEE_ID	  = IPMT.EXT_PMT_PARTY_ID(+)
  AND POS.PARTY_ID		  = TAX.PARTY_ID(+)
  AND TAX.PARTY_TAX_PROFILE_ID = ZXR.PARTY_TAX_PROFILE_ID(+)
  AND ZXR.REGISTRATION_NUMBER is not null
--  AND POZS.TERMS_ID = AT.TERM_ID(+)
--  AND NVL(AT.END_DATE_ACTIVE(+), SYSDATE+1) > SYSDATE


